#pragma once
#include "smartpointerhelp.h"
#include "glm_includes.h"
#include "drawable.h"
#include <array>
#include <atomic>
#include <cstddef>
#include <vector>

// C++ 11 allows us to define the size of an enum. This lets us use only one byte
// of memory to store our different block types. By default, the size of a C++ enum
// is that of an int (so, usually four bytes). This *does* limit us to only 256 different
// block types, but in the scope of this project we'll never get anywhere near that many.
enum BlockType : unsigned char
{
    EMPTY, GRASS, DIRT, STONE, WATER, SNOW, LAVA, BEDROCK, SAND, WOOD, LEAF,
    COAL_ORE, IRON_ORE, GOLD_ORE, DIAMOND_ORE, PLANK, BRICK,
    // Redstone family (Milestone 3): wire carries power from levers and
    // torches to lamps; ON variants glow via the lighting engine
    WIRE_OFF, WIRE_ON, TORCH, LEVER_OFF, LEVER_ON, LAMP_OFF, LAMP_ON
};

// The six cardinal directions in 3D space
enum Direction : unsigned char
{
    XPOS, XNEG, YPOS, YNEG, ZPOS, ZNEG
};

struct VBOData {
    std::vector<glm::vec4> opaqueVBO;
    std::vector<GLuint> opaqueIndex;
    std::vector<glm::vec4> transparentVBO;
    std::vector<GLuint> transparentIndex;
};

// One Chunk is a 16 x 256 x 16 section of the world,
// containing all the Minecraft blocks in that area.
// We divide the world into Chunks in order to make
// recomputing its VBO data faster by not having to
// render all the world at once, while also not having
// to render the world block by block.
//
// Threading contract: Chunks are created and destroyed on the main thread.
// A BlockTypeWorker owns m_blocks until it publishes m_blocksFilled; after
// that, workers only read block data. VBOData is written by at most one
// VBOWorker at a time (guarded by m_meshing/m_readyToBuffer on the Terrain
// side) and read by the main thread when uploading to the GPU.
class Chunk : public Drawable {
private:
    // All of the blocks contained within this Chunk
    std::array<BlockType, 65536> m_blocks;
    // The coordinates of the chunk's lower-left corner in world space
    int minX, minZ;
    // This Chunk's four neighbors to the north, south, east, and west.
    // Indexed by Direction; YPOS/YNEG stay null. Atomic because the main
    // thread links new neighbors while VBOWorkers read them.
    std::array<std::atomic<Chunk*>, 6> m_neighbors;

    // Helper function to check if a block is potentially visible
    bool isBlockVisible(int x, int y, int z) const;
    // The chunk at lateral offset (dx, dz) chunks from this one, reached
    // through the neighbor links; null if not instantiated. dx, dz in {-1,0,1}.
    const Chunk* chunkAt(int dx, int dz) const;
    // Builds the block/sky-light/block-light grids spanning this chunk plus
    // a 16-block border of its neighbors (see chunk.cpp for the layout).
    void buildLightGrid(std::vector<unsigned char> &cells,
                        std::vector<unsigned char> &skyLight,
                        std::vector<unsigned char> &blockLight) const;
    // For creating face data; bakes smooth per-vertex light + ambient
    // occlusion from the light grids into the color attribute
    void createFace(std::vector<glm::vec4> &interleaved, std::vector<GLuint> &indices,
                    glm::vec3 pos, Direction dir, BlockType type,
                    const unsigned char *cells,
                    const unsigned char *skyLight,
                    const unsigned char *blockLight);

public:
    Chunk(OpenGLContext* context, int x, int z);
    virtual ~Chunk();

    BlockType getLocalBlockAt(unsigned int x, unsigned int y, unsigned int z) const;
    BlockType getLocalBlockAt(int x, int y, int z) const;
    void setLocalBlockAt(unsigned int x, unsigned int y, unsigned int z, BlockType t);

    // Get adjacent chunk blocks that might affect VBO creation
    BlockType getAdjacentChunkBlockAt(int x, int y, int z) const;
    Chunk* getNeighbor(Direction dir) const { return m_neighbors[dir].load(std::memory_order_acquire); }

    void linkNeighbor(uPtr<Chunk>& neighbor, Direction dir);
    void createVBOdata() override;
    void destroyVBOdata() override;

    int getMinX() const;
    int getMinZ() const;

    // CPU-side interleaved mesh data, produced by createVBOdata() and
    // consumed by bufferInterleaved() on the main thread.
    VBOData vboData;
    void bufferInterleaved();

    // Climate value per (x, z) column in [0,255], written by the terrain
    // filler and baked into grass-top vertices for biome-tinted grass
    std::array<unsigned char, 256> m_climate{};

    // --- Multithreaded generation pipeline state (see Terrain) ---
    // Block data has been fully generated by a BlockTypeWorker.
    std::atomic<bool> m_blocksFilled{false};
    // A VBOWorker is currently writing vboData.
    std::atomic<bool> m_meshing{false};
    // vboData is complete and waiting for the main thread's GPU upload.
    std::atomic<bool> m_readyToBuffer{false};
};
